#!/usr/bin/env python3
"""
Generate Emberforge town map - Mountain mining town
Using Corneria metasprites (16x16)
"""

# Town dimensions
WIDTH = 32
HEIGHT = 32

print("🏘️  Generating Emberforge (Mountain Mining Town)...")
print("=" * 60)

# Corneria metasprite IDs
GRASS = 8
GRASS_SHADOW = 13
GRASS_SHADOW2 = 19
PATH = 4
PATH_CORNER_UL = 20
PATH_ALT = 22
PATH_CORNER_LR = 23
BRIDGE_H = 21
BRIDGE_V = 25
DOOR = 18
WINDOW_LARGE = 17
WINDOW_SMALL = 30
ROOF_TOP = 9
ROOF_MID = 11
ROOF_PEAK = 15
WATER = 10
WATER_WALL_SHADOW = 29
WATER_ROUND_SHADOW = 31
WELL = 33
WALL_L_HALF = 0
WALL_L_FULL = 6
WALL_R = 34
WALL_H1 = 1
WALL_H2 = 2
WALL_H3 = 5
FENCE = 24
SIGN_INN = 35
SIGN_ITEM = 28
SIGN_ARMOR = 26
SIGN_WEAPON = 27
TREE_TOP = 3
TREE_FULL = 7

# Initialize map with grass
town_map = [[GRASS for _ in range(WIDTH)] for _ in range(HEIGHT)]

print("\n🏗️  Building Emberforge...")

def place_building(x, y, width, roof_rows, name, window_type=WINDOW_LARGE, sign=None, peaked=False):
    """Place a building with proper NES FF structure"""
    print(f"  • Placing {name} at ({x},{y}) - {width} wide, {roof_rows + 2} rows tall")

    row = y

    # Row 0: Top of roof
    for dx in range(width):
        town_map[row][x + dx] = ROOF_TOP
    row += 1

    # Middle/bottom of roof
    for _ in range(roof_rows):
        for dx in range(width):
            if peaked and _ == roof_rows - 1 and dx == width // 2:
                town_map[row][x + dx] = ROOF_PEAK
            else:
                town_map[row][x + dx] = ROOF_MID
        row += 1

    # Wall with windows and door
    for dx in range(width):
        if dx == width // 2:
            town_map[row][x + dx] = DOOR
        else:
            town_map[row][x + dx] = window_type

    # Place sign above building
    if sign is not None and y > 0:
        town_map[y - 1][x + width // 2] = sign

# Create "mine entrance" (using wall tiles in upper area)
print("  • Creating mine entrance area...")
for x in range(10, 22):
    town_map[2][x] = WALL_H1  # Top edge
    town_map[3][x] = WALL_H2  # Bottom edge

# Mine entrance (door represents tunnel)
town_map[3][16] = DOOR
town_map[2][16] = ROOF_PEAK  # Peaked top above entrance

# Main path (cross pattern)
print("  • Creating paths...")
for y in range(6, HEIGHT - 2):
    town_map[y][15] = PATH
    town_map[y][16] = PATH

for x in range(4, 28):
    town_map[13][x] = PATH
    town_map[14][x] = PATH

# Place buildings
place_building(4, 8, 6, 2, "Inn", WINDOW_LARGE, SIGN_INN, peaked=True)
place_building(22, 8, 6, 2, "Item Shop", WINDOW_LARGE, SIGN_ITEM, peaked=True)
place_building(22, 18, 6, 2, "Equipment Shop", WINDOW_LARGE, SIGN_WEAPON, peaked=True)
place_building(4, 18, 5, 1, "House 1", WINDOW_SMALL, peaked=False)
place_building(4, 24, 5, 1, "House 2", WINDOW_SMALL, peaked=False)
place_building(10, 18, 4, 1, "House 3", WINDOW_SMALL, peaked=False)

# Add mountain town decorations
print("  • Adding decorations...")
# Well in center
town_map[15][20] = WELL

# Fence around mine entrance
for x in range(9, 12):
    town_map[5][x] = FENCE
for x in range(20, 23):
    town_map[5][x] = FENCE

# A few trees
tree_positions = [(2, 10), (2, 25), (29, 10), (29, 25)]
for tx, ty in tree_positions:
    if 0 <= tx < WIDTH and 0 <= ty < HEIGHT:
        town_map[ty][tx] = TREE_FULL

# Entrance
print("  • Creating entrance...")
for x in range(14, 18):
    town_map[30][x] = PATH
    town_map[31][x] = PATH

print("\n💾 Generating C code...")

with open("SRC/emberforge_map.c", "w") as f:
    f.write("""#include "town_map.h"
#include <string.h>

// Emberforge Map Data (32×32 tiles)
// Mountain mining town with mine entrance
// Using Corneria tileset (16x16 metasprites)
// Generated by generate_emberforge.py

static const uint8_t emberforge_tiles[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            f.write(f"{town_map[y][x]:3}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    # Collision map
    f.write("""static const uint8_t emberforge_collision[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    blocked_tiles = {
        ROOF_TOP, ROOF_MID, ROOF_PEAK,
        WALL_L_HALF, WALL_L_FULL, WALL_R, WALL_H1, WALL_H2, WALL_H3,
        WINDOW_LARGE, WINDOW_SMALL,
        FENCE, WELL, TREE_FULL, TREE_TOP,
        SIGN_INN, SIGN_ITEM, SIGN_ARMOR, SIGN_WEAPON,
        WATER, WATER_WALL_SHADOW, WATER_ROUND_SHADOW
    }

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            # Mine entrance door is walkable (leads to dungeon)
            if town_map[y][x] == DOOR and y <= 4:
                blocked = 0  # Mine entrance is walkable
            else:
                blocked = 1 if town_map[y][x] in blocked_tiles else 0
            f.write(f"{blocked}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    f.write("""void emberforge_init(TownMap* map) {
    map->width = TOWN_MAP_WIDTH;
    map->height = TOWN_MAP_HEIGHT;
    memcpy(map->tiles, emberforge_tiles, sizeof(emberforge_tiles));
    memcpy(map->collision, emberforge_collision, sizeof(emberforge_collision));
    map->entrance_x = 15;
    map->entrance_y = 31;
}
""")

print("✅ Generated: SRC/emberforge_map.c")
print(f"   Buildings: Inn, Item Shop, Equipment Shop, 3 Houses")
print(f"   Features: Mine entrance (north), Well, Trees, Fences, Cross paths")
print("\n✨ Emberforge generation complete!")
