#!/usr/bin/env python3
"""
Generate Windspire town map - Highland/sky town
Using Corneria metasprites (16x16)
"""

# Town dimensions
WIDTH = 32
HEIGHT = 32

print("🏘️  Generating Windspire (Highland Sky Town)...")
print("=" * 60)

# Corneria metasprite IDs
GRASS = 8
GRASS_SHADOW = 13
GRASS_SHADOW2 = 19
PATH = 4
PATH_CORNER_UL = 20
PATH_ALT = 22
PATH_CORNER_LR = 23
BRIDGE_H = 21
BRIDGE_V = 25
DOOR = 18
WINDOW_LARGE = 17
WINDOW_SMALL = 30
ROOF_TOP = 9
ROOF_MID = 11
ROOF_PEAK = 15
WATER = 10
WATER_WALL_SHADOW = 29
WATER_ROUND_SHADOW = 31
WELL = 33
WALL_L_HALF = 0
WALL_L_FULL = 6
WALL_R = 34
WALL_H1 = 1
WALL_H2 = 2
WALL_H3 = 5
FENCE = 24
SIGN_INN = 35
SIGN_ITEM = 28
SIGN_ARMOR = 26
SIGN_CLINIC = 16
TREE_TOP = 3
TREE_FULL = 7

# Initialize map with grass
town_map = [[GRASS for _ in range(WIDTH)] for _ in range(HEIGHT)]

print("\n🏗️  Building Windspire...")

def place_building(x, y, width, roof_rows, name, window_type=WINDOW_LARGE, sign=None, peaked=False):
    """Place a building with proper NES FF structure"""
    print(f"  • Placing {name} at ({x},{y}) - {width} wide, {roof_rows + 2} rows tall")

    row = y

    # Row 0: Top of roof
    for dx in range(width):
        town_map[row][x + dx] = ROOF_TOP
    row += 1

    # Middle/bottom of roof
    for _ in range(roof_rows):
        for dx in range(width):
            if peaked and _ == roof_rows - 1 and dx == width // 2:
                town_map[row][x + dx] = ROOF_PEAK
            else:
                town_map[row][x + dx] = ROOF_MID
        row += 1

    # Wall with windows and door
    for dx in range(width):
        if dx == width // 2:
            town_map[row][x + dx] = DOOR
        else:
            town_map[row][x + dx] = window_type

    # Place sign above building
    if sign is not None and y > 0:
        town_map[y - 1][x + width // 2] = sign

# Create elevated platform effect with fences
print("  • Creating highland platform...")
# Northern platform border
for x in range(3, 29):
    if x not in range(14, 18):  # Leave gap for entrance
        town_map[4][x] = FENCE

# Create main path (vertical through center with branches)
print("  • Creating paths...")
for y in range(5, HEIGHT - 2):
    town_map[y][15] = PATH
    town_map[y][16] = PATH

# Horizontal branch
for x in range(5, 27):
    town_map[12][x] = PATH
    town_map[13][x] = PATH

# Secondary horizontal branch
for x in range(8, 24):
    town_map[20][x] = PATH
    town_map[21][x] = PATH

# Place buildings
place_building(5, 6, 6, 2, "Inn", WINDOW_LARGE, SIGN_INN, peaked=True)
place_building(20, 6, 6, 2, "Item Shop", WINDOW_LARGE, SIGN_ITEM, peaked=True)
place_building(20, 15, 6, 2, "Equipment Shop", WINDOW_LARGE, SIGN_ARMOR, peaked=True)
place_building(5, 15, 5, 1, "House 1", WINDOW_SMALL, peaked=False)
place_building(5, 23, 5, 1, "House 2", WINDOW_SMALL, peaked=False)
place_building(12, 6, 4, 1, "House 3", WINDOW_SMALL, peaked=False)

# Add highland decorations
print("  • Adding decorations...")
# Central well
town_map[17][18] = WELL

# Trees at edges (windswept effect - fewer trees)
tree_positions = [(2, 8), (2, 22), (29, 8), (29, 22), (15, 2)]
for tx, ty in tree_positions:
    if 0 <= tx < WIDTH and 0 <= ty < HEIGHT:
        town_map[ty][tx] = TREE_FULL

# Decorative fences
for y in range(9, 12):
    town_map[y][11] = FENCE

# Small water feature (mountain spring)
town_map[24][12] = WATER
town_map[24][13] = WATER
town_map[25][12] = WATER
town_map[25][13] = WATER

# Entrance
print("  • Creating entrance...")
for x in range(14, 18):
    town_map[30][x] = PATH
    town_map[31][x] = PATH

print("\n💾 Generating C code...")

with open("SRC/windspire_map.c", "w") as f:
    f.write("""#include "town_map.h"
#include <string.h>

// Windspire Map Data (32×32 tiles)
// Highland sky town with mountain spring
// Using Corneria tileset (16x16 metasprites)
// Generated by generate_windspire.py

static const uint8_t windspire_tiles[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            f.write(f"{town_map[y][x]:3}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    # Collision map
    f.write("""static const uint8_t windspire_collision[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    blocked_tiles = {
        ROOF_TOP, ROOF_MID, ROOF_PEAK,
        WALL_L_HALF, WALL_L_FULL, WALL_R, WALL_H1, WALL_H2, WALL_H3,
        WINDOW_LARGE, WINDOW_SMALL,
        FENCE, WELL, TREE_FULL, TREE_TOP,
        SIGN_INN, SIGN_ITEM, SIGN_ARMOR, SIGN_CLINIC,
        WATER, WATER_WALL_SHADOW, WATER_ROUND_SHADOW
    }

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            blocked = 1 if town_map[y][x] in blocked_tiles else 0
            f.write(f"{blocked}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    f.write("""void windspire_init(TownMap* map) {
    map->width = TOWN_MAP_WIDTH;
    map->height = TOWN_MAP_HEIGHT;
    memcpy(map->tiles, windspire_tiles, sizeof(windspire_tiles));
    memcpy(map->collision, windspire_collision, sizeof(windspire_collision));
    map->entrance_x = 15;
    map->entrance_y = 31;
}
""")

print("✅ Generated: SRC/windspire_map.c")
print(f"   Buildings: Inn, Item Shop, Equipment Shop, 3 Houses")
print(f"   Features: Highland platform, Mountain spring, Well, Trees, Fences")
print("\n✨ Windspire generation complete!")
