#!/usr/bin/env python3
"""
Generate Greenleaf town map using Corneria metasprites
Each metasprite is 16x16 pixels (one logical tile)
"""

# Town dimensions
WIDTH = 32
HEIGHT = 32

print("🏘️  Generating Greenleaf Village (Corneria Tileset)...")
print("=" * 60)

# Corneria metasprite IDs (user-provided mapping)
# Ground
GRASS = 8
GRASS_SHADOW = 13
GRASS_SHADOW2 = 19

# Paths
PATH = 4
PATH_CORNER_UL = 20
PATH_ALT = 22
PATH_CORNER_LR = 23

# Bridges
BRIDGE_H = 21
BRIDGE_V = 25

# Doors & Windows
DOOR = 18
WINDOW_LARGE = 17
WINDOW_SMALL = 30

# Roofs
ROOF_TOP = 9
ROOF_MID = 11
ROOF_PEAK = 15

# Water
WATER = 10
WATER_WALL_SHADOW = 29
WATER_ROUND_SHADOW = 31

# Objects
WELL = 33

# Walls
WALL_L_HALF = 0
WALL_L_FULL = 6
WALL_R = 34
WALL_H1 = 1
WALL_H2 = 2
WALL_H3 = 5

# Fence
FENCE = 24

# Signs
SIGN_INN = 35
SIGN_ITEM = 28
SIGN_MAGIC = 14
SIGN_ARMOR = 26
SIGN_WEAPON = 27
SIGN_CLINIC = 16

# Trees
TREE_TOP = 3
TREE_FULL = 7

# Initialize map with grass
town_map = [[GRASS for _ in range(WIDTH)] for _ in range(HEIGHT)]

print("\n🏗️  Building Greenleaf village...")

def place_building(x, y, width, roof_rows, name, window_type=WINDOW_LARGE, sign=None, peaked=False):
    """
    Place a building with proper NES FF structure
    roof_rows: 1 or 2 (how many rows of tile 11 for middle/bottom of roof)
    peaked: whether to use peaked roof (tile 15) above door
    """
    print(f"  • Placing {name} at ({x},{y}) - {width} wide, {roof_rows + 2} rows tall")

    row = y

    # Row 0: Top of roof (tile 9)
    for dx in range(width):
        town_map[row][x + dx] = ROOF_TOP
    row += 1

    # Rows 1-(roof_rows): Middle/bottom of roof (tile 11)
    for _ in range(roof_rows):
        for dx in range(width):
            # Use peaked roof above door if requested
            if peaked and _ == roof_rows - 1 and dx == width // 2:
                town_map[row][x + dx] = ROOF_PEAK
            else:
                town_map[row][x + dx] = ROOF_MID
        row += 1

    # Final row: Wall with windows and door
    for dx in range(width):
        if dx == width // 2:
            town_map[row][x + dx] = DOOR
        else:
            town_map[row][x + dx] = window_type

    # Place sign above building if provided
    if sign is not None and y > 0:
        town_map[y - 1][x + width // 2] = sign

# Create main path (vertical through center)
print("  • Creating main path...")
for y in range(6, HEIGHT - 2):
    town_map[y][15] = PATH
    town_map[y][16] = PATH

# Horizontal path
for x in range(6, 26):
    town_map[12][x] = PATH
    town_map[13][x] = PATH

# Place buildings (x, y, width, roof_rows, name, window_type, sign, peaked)
place_building(4, 5, 6, 2, "Inn", WINDOW_LARGE, SIGN_INN, peaked=True)
place_building(22, 5, 6, 2, "Item Shop", WINDOW_LARGE, SIGN_ITEM, peaked=True)
place_building(22, 17, 6, 2, "Equipment Shop", WINDOW_LARGE, SIGN_ARMOR, peaked=True)
place_building(4, 17, 5, 1, "House 1", WINDOW_SMALL, peaked=False)
place_building(4, 25, 5, 1, "House 2", WINDOW_SMALL, peaked=False)
place_building(12, 5, 4, 1, "House 3", WINDOW_SMALL, peaked=False)

# Place well in town center
print("  • Placing well...")
town_map[14][20] = WELL

# Add some trees
print("  • Planting trees...")
tree_positions = [(2, 2), (2, 14), (2, 30), (29, 2), (29, 14), (29, 30), (18, 10)]
for tx, ty in tree_positions:
    if 0 <= tx < WIDTH and 0 <= ty < HEIGHT:
        town_map[ty][tx] = TREE_FULL

# Add decorative fences
print("  • Adding fences...")
for x in range(12, 16):
    town_map[10][x] = FENCE

# Entrance path
print("  • Creating entrance...")
for x in range(14, 18):
    town_map[30][x] = PATH
    town_map[31][x] = PATH

print("\n💾 Generating C code...")

with open("SRC/greenleaf_map.c", "w") as f:
    f.write("""#include "town_map.h"
#include <string.h>

// Greenleaf Village Map Data (32×32 tiles)
// Using Corneria tileset (16x16 metasprites)
// Generated by generate_greenleaf_corneria.py

static const uint8_t greenleaf_tiles[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            f.write(f"{town_map[y][x]:3}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    # Collision map
    f.write("""static const uint8_t greenleaf_collision[TOWN_MAP_HEIGHT][TOWN_MAP_WIDTH] = {
""")

    # Define blocked tiles
    blocked_tiles = {
        ROOF_TOP, ROOF_MID, ROOF_PEAK,
        WALL_L_HALF, WALL_L_FULL, WALL_R, WALL_H1, WALL_H2, WALL_H3,
        WINDOW_LARGE, WINDOW_SMALL,
        FENCE, WELL, TREE_FULL, TREE_TOP,
        SIGN_INN, SIGN_ITEM, SIGN_MAGIC, SIGN_ARMOR, SIGN_WEAPON, SIGN_CLINIC,
        WATER, WATER_WALL_SHADOW, WATER_ROUND_SHADOW
    }

    for y in range(HEIGHT):
        f.write("    {")
        for x in range(WIDTH):
            blocked = 1 if town_map[y][x] in blocked_tiles else 0
            f.write(f"{blocked}")
            if x < WIDTH - 1:
                f.write(",")
        f.write("}")
        if y < HEIGHT - 1:
            f.write(",")
        f.write(f"  // Row {y}\n")

    f.write("};\n\n")

    f.write("""void greenleaf_init(TownMap* map) {
    map->width = TOWN_MAP_WIDTH;
    map->height = TOWN_MAP_HEIGHT;
    memcpy(map->tiles, greenleaf_tiles, sizeof(greenleaf_tiles));
    memcpy(map->collision, greenleaf_collision, sizeof(greenleaf_collision));
    map->entrance_x = 15;
    map->entrance_y = 31;
}
""")

print("✅ Generated: SRC/greenleaf_map.c")
print(f"   Buildings: Inn, Item Shop, Equipment Shop, 3 Houses")
print(f"   Features: Well, Trees, Fences, Paths")
print("\n✨ Greenleaf village generation complete!")
